name = "ARMANets"
uuid = "33eca030-06a8-11eb-2ae2-bd410d8394ef"
authors = ["Timothy Lin <32549553+tmthyln@users.noreply.github.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[compat]
julia = "^1.3"
FFTW = "1"
Flux = "0.11"
Tullio = "0.2"
